input_file: ${input_file}
input_format: ${input_format}  # squad or rawdoc
output_dir: ${output_dir}
api_key: ${api_key}
max_examples: 1500
use_original: false  # Set true if input file contains original questions and would like to evaluate using the original data

pre_processors:
  - 
    _target_: nemo_retriever_sdg.DummyPreprocessor

qa_generator:
  _target_: nemo_retriever_sdg.SimpleQAGenerator
  api_key: ${api_key}
  model: mistralai/mixtral-8x22b-instruct-v0.1
  # mistralai/mixtral-8x7b-instruct-v0.1
  # nvidia/nemotron-4-340b-instruct
  # mistralai/mixtral-8x22b-instruct-v0.1
  base_url: https://integrate.api.nvidia.com/v1
  max_examples: ${max_examples}
  qa_generations_file: null
  generate_config:
    temperature: 0.5
    top_p: 1.0
    max_tokens: 2048
    stream: true
    parse_response: true
    num_questions: 3
    squad_format: true
    system_prompt: |
      Generate questions that are relevant to the input document provided. 
      Follow these General Instructions:
       - Questions must be completely answered by the input document.
       - Questions must be relevant to the input document.
       - Do not generate questions which requires looking at the input document to comprehend the question
       - Generate questions and answers to the generated questions.
       - Generated Questions should start with Question: 
       - Generated Answers should start with Answer:
      Follow this chain of thought when formulating questions:
      Step 1: Identify key phrases and entities in the input document
      Step 2: Generate questions based on those key phrases and entities

      Compress any compounded questions to shorter questions to sound realistic. Questions can also be in the form of short phrases.
      Use the following examples as guidelines.
      
      Examples:

      Input document:
      In November 2013, Senate Democrats led by Harry Reid used the nuclear option to eliminate the 60 - vote rule on executive branch nominations and federal judicial appointments, but not for the Supreme Court. In April 2017, Senate Republicans led by Mitch McConnell extended the nuclear option to Supreme Court and the nomination of Neil Gorsuch ending the debate.
      
      Question:
      who changed the senate rules for supreme court nominees?

      Input Document:
      The First Pan-African Conference was held in London from 23 to 25 July 1900 (just prior to the Paris Exhibition of 1900 "in order to allow tourists of African descent to attend both events \'\'). Organized primarily by the Trinidadian barrister Henry Sylvester Williams, it took place in Westminster Town Hall (now Caxton Hall) and was attended by 37 delegates and about 10 other participants and observers from Africa, the West Indies, the US and the UK, including Samuel Coleridge Taylor (the youngest delegate), John Alcindor, Dadabhai Naoroji, John Archer, Henry Francis Downing, and W.E.B. Du Bois, with Bishop Alexander Walters of the AME Zion Church taking the chair. Du Bois played a leading role, drafting a letter ("Address to the Nations of the World \'\') to European leaders appealing to them to struggle against racism, to grant colonies in Africa and the West Indies the right to self - government and demanding political and other rights for African Americans.

      Question:
      which figure in the pan-african movement organized the first pan-african conference in 1900 apex?

      Input Document:
      After the outbreak of World War I the Defence of the Realm Act was passed by Parliament in 1914. One section of the Act concerned the hours pubs could sell alcohol, as it was believed that alcohol consumption would interfere with the war effort. It restricted opening hours for licensed premises to luncheon (12: 00 to 14: 40) and supper (18: 30 to 21: 30). In the late 1980s the licensing laws in England and Wales became less restricted and allowed pubs to allow the consumption of alcohol on the premises from 11: 00 until 23: 00, although nightclubs were allowed to stay open much later. Significantly revised rules were introduced in November 2005, when hour limits were scrapped, and pubs were allowed to apply for licences as permissive as "24 hours a day \'\'. In practice, most pubs chose to apply for more restrictive licences.

      Question:
      when did all day drinking start in england?

      Input Document:
      The Washington Nationals are a professional baseball team based in Washington, D.C. The Nationals compete in Major League Baseball (MLB) as a member club of the National League (NL) East division. From 2005 to 2007, the team played in RFK Stadium; since 2008 their home stadium has been Nationals Park on South Capitol Street in Southeast D.C., near the Anacostia River.

      Question:
      where are the washington nationals based out of?

      Input Document:
      Hugs and kisses or xoxo is a term used for expressing sincerity, faith, love, or good friendship at the end of a written letter, email or SMS text message.

      Question:
      what is the symbol for hugs and kisses?
      
    user_prompt_template: |
      Generate {num_questions} questions and corresponding answers based on Input Document.

      Input Document:
      {document}   

easiness_filter:
  _target_: nemo_retriever_sdg.EasinessFilter
  filter_cfg:
    filter_threshold: 0.75
    embedding_model: "intfloat/e5-large-unsupervised"
    batch_size: 16

answerability_filter:
  _target_: nemo_retriever_sdg.AnswerabilityFilter
  filter_cfg:
    base_url: "https://integrate.api.nvidia.com/v1"
    api_key: ${api_key}
    model_name: "meta/llama3-70b-instruct"
    num_criteria: 4  # Number of criteria to parse from the response. It must be alined with the prompt template
    system_prompt: |
      You are an evaluator who is rating questions to given context passages based on the given criteria. Assess the given question for clarity and answerability given enough domain knowledge, consider the following evaluation criterion:
      Criterion 1 - Can the question be understood and answered without needing additional context or access to external references not provided within the question itself? Questions should be self-contained, meaning they do not rely on specific documents, tables, or prior knowledge not shared within the question.
      Criterion 2 - Is it clear what type of answer or information the question seeks? The question should convey its purpose without ambiguity, allowing for a direct and relevant response.
      Criterion 3 - Does the content in the context contain information that can answer the question or part of the question?
      Criterion 4 - Does the content in the context completely answer the question?
      
      Provide your response in a mandatory dictionary format, and a short explanation of the rating like
      {
      \"criterion_1_explanation\": "<Brief explanation of why criterion_1 was satisfied or not satisfied>",
      \"criterion_1\": "<Y/N>",
      \"criterion_2_explanation\":  "<State the purpose of the question and justify why it was satisfied or not satisfied>",
      \"criterion_2\": "<Y/N>",
      \"criterion_3_explanation\": "<Show what parts of the content contain relevant information to the question if this criterion is satisfied, state why the information is irrelevant if unsatisfied>",
      \"criterion_3\": "<Y/N>",
      \"criterion_4_explanation\": "<Extract spans from the content that help completely answer the question if criterion is satisfied, state what parts are missing if not satisfied>",
      \"criterion_4\": "<Y/N>"
      }
      Provide only the dictionary response and nothing else.    
    
    user_prompt_template: |
      Context Passage:
      {context}
      Question:
      {question}
      
filters:
  -
    ${answerability_filter}
<<<<<<< HEAD
  - 
    ${easiness_filter}
=======
  # - 
  #   ${easiness_filter}
>>>>>>> 3d49ef8 (added config-nq and config-fiqa)
  

post_processors:
  - 
    _target_: nemo_retriever_sdg.DivergenceCalculator

analyzers:
  -
    _target_: nemo_retriever_sdg.QuestionLengthAnalyzer
  -
    _target_: nemo_retriever_sdg.LexicalDivergenceAnalyzer
